In [1]:
import urllib
import bs4
import re
import pandas as pd
from urllib import request
import datetime
import time
import re
import codecs

In [81]:
## création d"une liste de dates 
liste_dates=[]
j = datetime.date(2020,5,31)
while j >= datetime.date(2020, 4, 1):
    liste_dates.append( j.strftime("%Y/%m/%d"))
    j = j + datetime.timedelta(days=-1)
print(len(liste_dates))
liste_dates[:1]

61

['2020/05/31']

In [82]:
def trouve_categorie(text):
    text = str(text[1:]).lower() # mettre les mots en minuscule
    text = text.split("/")[0]
    return text

In [83]:
# création de 2 listes l'une contient les articles, l'autre le jour de publication.
liste_articles =[]
liste_jour_publication = []
liste_cat1 =[]
liste_cat2 =[]
liste_auteurs =[]
liste_t =[]
df_closer = pd.DataFrame()

for d in liste_dates:
    page_explorée = "https://www.closermag.fr/archives/" + str(d) + "/"
    req_1 = urllib.request.Request(page_explorée,headers={'User-Agent': 'Mozilla/5.0'})
    request_text = request.urlopen(req_1).read()
    html = codecs.decode(request_text, 'utf-8')
    page_jour = bs4.BeautifulSoup(html, "lxml")
    for section in page_jour.findAll("div", {"class" :"list-archives"}):
        for a in section.findAll("a"):
            cat = trouve_categorie(a.get('href', None))
            titre = a.getText()
            df_closer = df_closer.append({'titre':titre,'jour_publication':d ,'categorie':cat}, ignore_index=True)
df_closer

,categorie,jour_publication,titre
0,royautes,2020/05/31,Kate Middleton : pourquoi elle a changé ses bi...
1,people,2020/05/31,Gad Elmaleh : qui était sa première femme Anne...
2,politique,2020/05/31,Bernard Tapie : pourquoi sa fille Sophie n'arr...
3,people,2020/05/31,Nabilla aux anges : son petit frère Tarek va b...
4,royautes,2020/05/31,Elizabeth II : pourquoi sa mère a laissé plus ...
...,...,...,...
1743,people,2020/04/01,Christina Milian : cet achat complètement impu...
1744,people,2020/04/01,Matt Pokora confiné : il partage une photo tro...
1745,royautes,2020/04/01,"Meghan, Harry et Archie : que font-ils pendant..."
1746,royautes,2020/04/01,Megxit : quels membres de la famille royale su...
1747,people,2020/04/01,"Mort de Pape Diouf : Florian Thauvin, Djibril ..."

In [84]:
df_closer = df_closer[['titre','jour_publication','categorie']]
df_closer

,titre,jour_publication,categorie
0,Kate Middleton : pourquoi elle a changé ses bi...,2020/05/31,royautes
1,Gad Elmaleh : qui était sa première femme Anne...,2020/05/31,people
2,Bernard Tapie : pourquoi sa fille Sophie n'arr...,2020/05/31,politique
3,Nabilla aux anges : son petit frère Tarek va b...,2020/05/31,people
4,Elizabeth II : pourquoi sa mère a laissé plus ...,2020/05/31,royautes
...,...,...,...
1743,Christina Milian : cet achat complètement impu...,2020/04/01,people
1744,Matt Pokora confiné : il partage une photo tro...,2020/04/01,people
1745,"Meghan, Harry et Archie : que font-ils pendant...",2020/04/01,royautes
1746,Megxit : quels membres de la famille royale su...,2020/04/01,royautes
1747,"Mort de Pape Diouf : Florian Thauvin, Djibril ...",2020/04/01,people

In [85]:
df_closer.to_csv('df_closerBis.csv', index=False)