In [1]:
import sklearn
import numpy as np
from sklearn.model_selection import train_test_split
import urllib
import bs4
import re
import pandas as pd
from urllib import request
import datetime
import time
import re
import pickle

## LE MONDE

In [2]:
df_lemonde = pd.read_csv("df_titres_lemonde.csv")
df_lemonde = df_lemonde[['titre','jour_publication','auteur']]
df_lemonde['journal']='Le Monde'
df_lemonde

,titre,jour_publication,auteur,journal
0,"Pour les galeries d’art, une situation moins s...",01-02-2021,['Roxana Azimi'],Le Monde
1,Quand la masturbation provoque une hémorragie ...,01-02-2021,['Marc Gozlan'],Le Monde
2,Les pistes de la France pour améliorer les ter...,01-02-2021,['Julien Bouissou'],Le Monde
3,Facebook et Apple se livrent une guerre ouverte,01-02-2021,['Alexandre Piquard'],Le Monde
4,"Kent Walker : « Google agit selon les lois, et...",01-02-2021,['Kent Walker'],Le Monde
...,...,...,...,...
118300,Corée du Nord : Kim Jong-un dit vouloir amélio...,01-01-2018,['Le Monde avec AFP et Reuters'],Le Monde
118301,Les célébrations du Nouvel An 2018 en images,01-01-2018,"['Le Monde avec AFP, AP et Reuters']",Le Monde
118302,Marseille : un homme tué à la kalachnikov la n...,01-01-2018,['Le Monde avec AFP'],Le Monde
118303,Douze morts dans un accident d’avion au Costa ...,01-01-2018,['Le Monde avec AFP'],Le Monde
118304,Iran : le président Rohani sur la corde raide ...,01-01-2018,['Ghazal Golshiri'],Le Monde

## LIBERATION

In [3]:
df_liberation1 = pd.read_csv("df_titres_liberation.csv")
df_liberation2 = pd.read_csv("df_titres_liberation2.csv")
df_liberation3 =pd.read_csv("df_titres_liberation3.csv")
df_liberation4 =pd.read_csv("df_titres_liberation4.csv")
df_liberation = pd.concat([df_liberation1,df_liberation2,df_liberation3,df_liberation4])
df_liberation = df_liberation[['titre','jour_publication']]
df_liberation['journal']='Libération'
df_liberation

,titre,jour_publication,journal
0,"A Canal + et CNews, silence radio chez les jou...",2021/02/03,Libération
1,«Voracisme» : «Pourquoi ce ne sont pas les Bla...,2021/02/03,Libération
2,Internat pour les enfants : «Il est pensé pour...,2021/02/03,Libération
3,Jeu de milliards à trois bandes pour les média...,2021/02/03,Libération
4,La présence du virus dans les eaux usées en Il...,2021/02/03,Libération
...,...,...,...
1076,Veolia-Suez : bataille d’eau entre géants de l...,2020/09/10,Libération
1077,Eau : la tentation du retour à la gestion publ...,2020/09/10,Libération
1078,"Hôpital de la Timone : en réanimation, «c’est ...",2020/09/10,Libération
1079,Procès des attentats de janvier 2015 : des mot...,2020/09/10,Libération
1080,Covid-19 : des réponses locales à une dégradat...,2020/09/10,Libération

## LES ECHOS

df_lesEchos = pd.read_csv("titres_lesEchos_bis.csv")
df_lesEchos = df_lesEchos.rename(columns={'jour_publication':'jour_precis'})
df_lesEchos['jour_publication']='2018/02'

df_lesEchos2 = pd.read_csv("titres_lesEchos_12_2020.csv")
df_lesEchos2 =df_lesEchos2.rename(columns={'jour_publication':'jour_precis'})
df_lesEchos2['jour_publication']='2018/12'

df_lesEchos3 = pd.read_csv("titres_lesEchos_aout_nov_2020.csv")
df_lesEchos3 =df_lesEchos3.rename(columns={'jour_publication':'jour_precis'})
df_lesEchos3['jour_publication']=df_lesEchos3.jour_precis

df_lesEchos = pd.concat([df_lesEchos,df_lesEchos2,df_lesEchos3])
df_lesEchos = df_lesEchos[["titre",'jour_publication','auteur']]
df_lesEchos['journal']= "Les Echos"
df_lesEchos

## LE PARISIEN

In [4]:
df_Parisien = pd.read_csv('LeParisien.csv')
df_Parisien2 = pd.read_csv('leParisiendebut_2021.csv')
df_Parisien3 = pd.read_csv('leParisien_tout_debut_2021.csv')
df_Parisien = pd.concat([df_Parisien,df_Parisien2,df_Parisien3])
df_Parisien = df_Parisien[['titre','jour_publication']]
df_Parisien['journal']= "Le Parisien"
df_Parisien

,titre,jour_publication,journal
0,Procès des écoutes : Nicolas Sarkozy condamné ...,2021/01-03-2021,Le Parisien
1,Tests salivaires à l’école : ce sont des «pers...,2021/01-03-2021,Le Parisien
2,«Ils ne travaillaient plus ensemble depuis déj...,2021/01-03-2021,Le Parisien
3,Relance : l’épargne des Français ne sera pas t...,2021/01-03-2021,Le Parisien
4,FC Barcelone : opération policière au siège du...,2021/01-03-2021,Le Parisien
...,...,...,...
1871,"Cette nuit, le couvre-feu de 20 heures s’est s...",2021/16-01-2021,Le Parisien
1872,"Plongée au cœur de la Pléiade, 89 ans, collect...",2021/16-01-2021,Le Parisien
1873,"VIDÉO. Déguisement , animaux,cuisine... Un com...",2021/16-01-2021,Le Parisien
1874,"Agy, ou l’art de distribuer de l’amour aux san...",2021/16-01-2021,Le Parisien
1875,Covid-19 : l’Inde entame sa campagne vaccinale...,2021/16-01-2021,Le Parisien

## L'EXPRESS

In [5]:
df_express = pd.read_csv('titres_Lexpress.csv')
df_express2 = pd.read_csv('titres_Lexpress_dec2020.csv')
df_express3 = pd.read_csv('titres_Lexpress_oct_nov2020.csv')
df_express = pd.concat([df_express,df_express2,df_express3])
df_express = df_express[['titre','jour_publication']]
df_express['journal']= "L'Express"
df_express

,titre,jour_publication,journal
0,Palmarès des meilleures ventes littéraires : E...,2021/03/01,L'Express
1,Affaires des écoutes : Nicolas Sarkozy condamn...,2021/03/01,L'Express
2,"Courrier des lecteurs : Eric Zemmour, Covid, A...",2021/03/01,L'Express
3,"En Floride, les militants galvanisés par le re...",2021/03/01,L'Express
4,"Affaire des ""écoutes"": Nicolas Sarkozy condamn...",2021/03/01,L'Express
...,...,...,...
3009,Vers un 4e mandat pour le président LR du Séna...,2020/10/01,L'Express
3010,"Le fonds Ardian, ""soutenu"" par Suez, ""intéress...",2020/10/01,L'Express
3011,Charlie Hebdo raconte ses 50 ans de lutte pour...,2020/10/01,L'Express
3012,Comment fonctionnent les pétitions citoyennes ...,2020/10/01,L'Express
3013,"Taxé de ""honte nationale"", Trump tente t'étein...",2020/10/01,L'Express

In [7]:
df_closer = pd.read_csv('df_closer.csv')
df_closer2 = pd.read_csv('df_closerBis.csv')
df_closer = pd.concat([df_closer,df_closer2])
df_closer = df_closer[['titre','jour_publication']]
df_closer['journal']= "Closer"
df_closer

,titre,jour_publication,journal
0,Prison ferme pour Nicolas Sarkozy : ces vieux ...,2021/03/02,Closer
1,Brigitte Macron : sa lettre personnelle et tou...,2021/03/02,Closer
2,Gérard Louvin accusé de complicité de viols : ...,2021/03/02,Closer
3,Prison ferme pour Nicolas Sarkozy : ces vieux ...,2021/03/01,Closer
4,Brigitte Macron : sa lettre personnelle et tou...,2021/03/01,Closer
...,...,...,...
1743,Christina Milian : cet achat complètement impu...,2020/04/01,Closer
1744,Matt Pokora confiné : il partage une photo tro...,2020/04/01,Closer
1745,"Meghan, Harry et Archie : que font-ils pendant...",2020/04/01,Closer
1746,Megxit : quels membres de la famille royale su...,2020/04/01,Closer
1747,"Mort de Pape Diouf : Florian Thauvin, Djibril ...",2020/04/01,Closer

In [9]:
df = pd.concat([df_lemonde[:8000], df_liberation, df_Parisien, df_express,df_closer])
df.jour_publication = df.jour_publication.map(lambda x: x.replace("/","-"))
df

,titre,jour_publication,auteur,journal
0,"Pour les galeries d’art, une situation moins s...",01-02-2021,['Roxana Azimi'],Le Monde
1,Quand la masturbation provoque une hémorragie ...,01-02-2021,['Marc Gozlan'],Le Monde
2,Les pistes de la France pour améliorer les ter...,01-02-2021,['Julien Bouissou'],Le Monde
3,Facebook et Apple se livrent une guerre ouverte,01-02-2021,['Alexandre Piquard'],Le Monde
4,"Kent Walker : « Google agit selon les lois, et...",01-02-2021,['Kent Walker'],Le Monde
...,...,...,...,...
1743,Christina Milian : cet achat complètement impu...,2020-04-01,NaN,Closer
1744,Matt Pokora confiné : il partage une photo tro...,2020-04-01,NaN,Closer
1745,"Meghan, Harry et Archie : que font-ils pendant...",2020-04-01,NaN,Closer
1746,Megxit : quels membres de la famille royale su...,2020-04-01,NaN,Closer
1747,"Mort de Pape Diouf : Florian Thauvin, Djibril ...",2020-04-01,NaN,Closer

In [10]:
df.to_csv('data.csv', index=False)