In [1]:
import sklearn
import numpy as np
import pandas as pd
import datetime
import time
import re

## LE MONDE

In [3]:
df_lemonde = pd.read_csv("csv/df_titres_lemonde.csv")
df_lemonde = df_lemonde[['titre','jour_publication','categorie']]
df_lemonde.jour_publication = df_lemonde.jour_publication.map(lambda x : datetime.datetime.strptime(x,'%d-%m-%Y'))
df_lemonde['journal']='Le Monde'
df_lemonde

,titre,jour_publication,categorie,journal
0,"Pour les galeries d’art, une situation moins s...",2021-02-01,economie,Le Monde
1,Quand la masturbation provoque une hémorragie ...,2021-02-01,NaN,Le Monde
2,Les pistes de la France pour améliorer les ter...,2021-02-01,economie,Le Monde
3,Facebook et Apple se livrent une guerre ouverte,2021-02-01,economie,Le Monde
4,"Kent Walker : « Google agit selon les lois, et...",2021-02-01,pixels,Le Monde
...,...,...,...,...
118300,Corée du Nord : Kim Jong-un dit vouloir amélio...,2018-01-01,asie-pacifique,Le Monde
118301,Les célébrations du Nouvel An 2018 en images,2018-01-01,NaN,Le Monde
118302,Marseille : un homme tué à la kalachnikov la n...,2018-01-01,police-justice,Le Monde
118303,Douze morts dans un accident d’avion au Costa ...,2018-01-01,ameriques,Le Monde
118304,Iran : le président Rohani sur la corde raide ...,2018-01-01,proche-orient,Le Monde

In [6]:
df_lemonde3 = pd.read_csv("csv/df_titres_lemonde_last.csv")
df_lemonde3 = df_lemonde3[['titre','jour_publication','categorie']]
df_lemonde3.jour_publication = df_lemonde3.jour_publication.map(lambda x : datetime.datetime.strptime(x,'%d-%m-%Y'))
df_lemonde3['journal']='Le Monde'
df_lemonde3

,titre,jour_publication,categorie,journal
0,Castex annonce un durcissement des peines cont...,2021-05-10,societe,Le Monde
1,Nouvel incident dans le détroit d’Ormuz entre ...,2021-05-10,international,Le Monde
2,La France est « en train de sortir durablement...,2021-05-10,planete,Le Monde
3,« Agent orange » : la justice déboute Tran To Nga,2021-05-10,societe,Le Monde
4,Sciences Po tourne la page Olivier Duhamel,2021-05-10,societe,Le Monde
...,...,...,...,...
9518,Emmanuel Macron veut rassurer à propos de la c...,2021-02-03,politique,Le Monde
9519,"En Russie, la contestation au temps des grands...",2021-02-03,international,Le Monde
9520,Qui recrutera un cadre avant le printemps ?,2021-02-03,emploi,Le Monde
9521,"Richard Malka, avocat de « Charlie Hebdo » en ...",2021-02-03,societe,Le Monde
9522,"Neige, glissades et avalanche, sept films pour...",2021-02-03,cinema,Le Monde

## LIBERATION

In [3]:
datetime.datetime.strptime('2021-02-03','%Y-%m-%d')

datetime.datetime(2021, 2, 3, 0, 0)

In [4]:
df_liberation1 = pd.read_csv("csv/df_titres_liberation.csv")
df_liberation2 = pd.read_csv("csv/df_titres_liberation2.csv")
df_liberation3 =pd.read_csv("csv/df_titres_liberation3.csv")
df_liberation4 =pd.read_csv("csv/df_titres_liberation4.csv")
df_liberation = pd.concat([df_liberation1,df_liberation2,df_liberation3,df_liberation4])
df_liberation.categorie = df_liberation.categorie.map(lambda x: x.lower())
df_liberation = df_liberation[['titre','jour_publication','categorie']]
df_liberation['journal']='Libération'
df_liberation.jour_publication = df_liberation.jour_publication.map(lambda x: datetime.datetime.strptime(str(x),'%Y/%m/%d'))
df_liberation

,titre,jour_publication,categorie,journal
0,"A Canal + et CNews, silence radio chez les jou...",2021-02-03,economie,Libération
1,«Voracisme» : «Pourquoi ce ne sont pas les Bla...,2021-02-03,société,Libération
2,Internat pour les enfants : «Il est pensé pour...,2021-02-03,société,Libération
3,Jeu de milliards à trois bandes pour les média...,2021-02-03,economie,Libération
4,La présence du virus dans les eaux usées en Il...,2021-02-03,checknews,Libération
...,...,...,...,...
1076,Veolia-Suez : bataille d’eau entre géants de l...,2020-09-10,société,Libération
1077,Eau : la tentation du retour à la gestion publ...,2020-09-10,société,Libération
1078,"Hôpital de la Timone : en réanimation, «c’est ...",2020-09-10,société,Libération
1079,Procès des attentats de janvier 2015 : des mot...,2020-09-10,société,Libération
1080,Covid-19 : des réponses locales à une dégradat...,2020-09-10,société,Libération

In [2]:
df_liberation2 = pd.read_csv("csv/titres_liberation2.csv")
df_liberation2.categorie = df_liberation2.categorie.map(lambda x: x.lower())
df_liberation2 = df_liberation2[['titre','jour_publication','categorie']]
df_liberation2['journal']='Libération'
df_liberation2.jour_publication = df_liberation2.jour_publication.map(lambda x: datetime.datetime.strptime(str(x),'%Y/%m/%d'))
df_liberation2

,titre,jour_publication,categorie,journal
0,Nathalie Loiseau : «Dire “on va à la pêche au ...,2021-03-01,politique,Libération
1,Truffe blanche : la France s’appuie sur le cha...,2021-03-01,lifestyle,Libération
2,"Belleville, inventaire d’exil",2021-03-01,culture,Libération
3,Petite guerre froide entre amis,2021-03-01,idées et débats,Libération
4,Manifeste pour les 51 %,2021-03-01,idées et débats,Libération
...,...,...,...,...
1408,"Les covidosceptiques, une galaxie aussi habile...",2021-02-04,société,Libération
1409,6 février 1934 : des ligues fascistes à Généra...,2021-02-04,idées et débats,Libération
1410,"«Spare Ribs», Sleaford Mods envoie du steak",2021-02-04,culture,Libération
1411,"«Perdre cinq minutes sur un trajet de 40km, si...",2021-02-04,société,Libération
1412,Capitole : le procureur démocrate demande à Tr...,2021-02-04,international,Libération

In [8]:
df_liberation3 = pd.read_csv("csv/titres_liberation3.csv")
df_liberation3.categorie = df_liberation3.categorie.map(lambda x: x.lower())
df_liberation3 = df_liberation3[['titre','jour_publication','categorie']]
df_liberation3['journal']='Libération'
df_liberation3.jour_publication = df_liberation3.jour_publication.map(lambda x: datetime.datetime.strptime(str(x),'%Y/%m/%d'))
df_liberation3

,titre,jour_publication,categorie,journal
0,"Archie Shepp et Jason Moran, deux âmes en scène",2021-03-02,culture,Libération
1,"«La Déferlante», la nouvelle vague féministe",2021-03-02,idées et débats,Libération
2,"«Vertigo Days», The Notwist again",2021-03-02,culture,Libération
3,Adieu à la viande,2021-03-02,idées et débats,Libération
4,Jean-Pierre Filiu : «Nous assistons à la naiss...,2021-03-02,idées et débats,Libération
...,...,...,...,...
2647,L’indemnisation des chômeurs en fin de droits ...,2021-04-19,economie,Libération
2648,Super Ligue : «Cela devient de la ségrégation»,2021-04-19,sports,Libération
2649,«La Super Ligue de foot va accentuer les déséq...,2021-04-19,sports,Libération
2650,Le bilan brésilien du Covid-19 est-il pire que...,2021-04-19,checknews,Libération
2651,"Derrière l’enlèvement de Mia, l’«opération Lima»",2021-04-19,société,Libération

In [3]:
df_liberation4 = pd.read_csv("csv/titres_liberation4.csv")
df_liberation4.categorie = df_liberation4.categorie.map(lambda x: x.lower())
df_liberation4 = df_liberation4[['titre','jour_publication','categorie']]
df_liberation4['journal']='Libération'
df_liberation4.jour_publication = df_liberation4.jour_publication.map(lambda x: datetime.datetime.strptime(str(x),'%Y/%m/%d'))
df_liberation4

,titre,jour_publication,categorie,journal
0,«Bidenomics» : l’économie selon Joe Biden,2021-04-20,opinions,Libération
1,Affaire Sarah Halimi : une irresponsabilité po...,2021-04-20,police / justice,Libération
2,"Angleterre, Italie, Espagne : tollé des suppor...",2021-04-20,football,Libération
3,Animaux dans les labos : deux salariées dénonc...,2021-04-20,checknews,Libération
4,"Cassis de Dijon et champagne, par noms et par ...",2021-04-20,economie,Libération
...,...,...,...,...
1178,"«Time Capsule 2045», les as de la cachette",2021-05-10,arts,Libération
1179,"Turner Prize, le temps des militants",2021-05-10,arts,Libération
1180,Rwanda : «Nous avons changé de méthode pour tr...,2021-05-10,afrique,Libération
1181,"Michel Fourniret, la fin de l’«ogre des Ardennes»",2021-05-10,police / justice,Libération
1182,Grève dans les centres des impôts : «On nous d...,2021-05-10,economie,Libération

## LES ECHOS

df_lesEchos = pd.read_csv("csv/titres_lesEchos_bis.csv")
df_lesEchos = df_lesEchos.rename(columns={'jour_publication':'jour_precis'})
df_lesEchos['jour_publication']='2018/02'

df_lesEchos2 = pd.read_csv("csv/titres_lesEchos_12_2020.csv")
df_lesEchos2 =df_lesEchos2.rename(columns={'jour_publication':'jour_precis'})
df_lesEchos2['jour_publication']='2018/12'

df_lesEchos3 = pd.read_csv("csv/titres_lesEchos_aout_nov_2020.csv")
df_lesEchos3 =df_lesEchos3.rename(columns={'jour_publication':'jour_precis'})
df_lesEchos3['jour_publication']=df_lesEchos3.jour_precis

df_lesEchos = pd.concat([df_lesEchos,df_lesEchos2,df_lesEchos3])
df_lesEchos = df_lesEchos#[["titre",'jour_publication','auteur']]
df_lesEchos['journal']= "Les Echos"
df_lesEchos

## LE PARISIEN

In [5]:
# PAS DE CATGEORIE DE SCRAPPER
df_Parisien = pd.read_csv('csv/LeParisien.csv')
df_Parisien2 = pd.read_csv('csv/leParisiendebut_2021.csv')
df_Parisien3 = pd.read_csv('csv/leParisien_tout_debut_2021.csv')
df_Parisien = pd.concat([df_Parisien,df_Parisien2,df_Parisien3])
df_Parisien.jour_publication = df_Parisien.jour_publication.map(lambda x : datetime.datetime.strptime(x[5:],'%d-%m-%Y'))
df_Parisien['journal']= "Le Parisien"
df_Parisien

,auteur,jour_publication,titre,journal
0,Par Le Parisien,2021-03-01,Procès des écoutes : Nicolas Sarkozy condamné ...,Le Parisien
1,Par Le Parisien avec AFP,2021-03-01,Tests salivaires à l’école : ce sont des «pers...,Le Parisien
2,Par Emmanuel Marolle,2021-03-01,«Ils ne travaillaient plus ensemble depuis déj...,Le Parisien
3,Par Le Parisien avec AFP,2021-03-01,Relance : l’épargne des Français ne sera pas t...,Le Parisien
4,Par Le Parisien avec AFP,2021-03-01,FC Barcelone : opération policière au siège du...,Le Parisien
...,...,...,...,...
1871,Par Anthony Lieures,2021-01-16,"Cette nuit, le couvre-feu de 20 heures s’est s...",Le Parisien
1872,Par Elisa Thévenet,2021-01-16,"Plongée au cœur de la Pléiade, 89 ans, collect...",Le Parisien
1873,Par Marion Ducrocq,2021-01-16,"VIDÉO. Déguisement , animaux,cuisine... Un com...",Le Parisien
1874,Par Pauline Darvey,2021-01-16,"Agy, ou l’art de distribuer de l’amour aux san...",Le Parisien
1875,"Par Le Parisien, avec AFP",2021-01-16,Covid-19 : l’Inde entame sa campagne vaccinale...,Le Parisien

## L'EXPRESS

In [6]:
df_express = pd.read_csv('csv/titres_Lexpress.csv')
df_express2 = pd.read_csv('csv/titres_Lexpress_dec2020.csv')
df_express3 = pd.read_csv('csv/titres_Lexpress_oct_nov2020.csv')
df_express = pd.concat([df_express,df_express2,df_express3])
df_express = df_express[['titre','jour_publication','categorie']]
df_express.categorie = df_express.categorie.map(lambda x: x.lower())
df_express.jour_publication = df_express.jour_publication.map(lambda x: (datetime.datetime.strptime(x,'%Y/%m/%d') ))
df_express['journal']= "L'Express"
df_express

,titre,jour_publication,categorie,journal
0,Palmarès des meilleures ventes littéraires : E...,2021-03-01,culture,L'Express
1,Affaires des écoutes : Nicolas Sarkozy condamn...,2021-03-01,politique,L'Express
2,"Courrier des lecteurs : Eric Zemmour, Covid, A...",2021-03-01,actualité,L'Express
3,"En Floride, les militants galvanisés par le re...",2021-03-01,amerique du nord,L'Express
4,"Affaire des ""écoutes"": Nicolas Sarkozy condamn...",2021-03-01,société,L'Express
...,...,...,...,...
3009,Vers un 4e mandat pour le président LR du Séna...,2020-10-01,actualité,L'Express
3010,"Le fonds Ardian, ""soutenu"" par Suez, ""intéress...",2020-10-01,société,L'Express
3011,Charlie Hebdo raconte ses 50 ans de lutte pour...,2020-10-01,actualité,L'Express
3012,Comment fonctionnent les pétitions citoyennes ...,2020-10-01,politique,L'Express
3013,"Taxé de ""honte nationale"", Trump tente t'étein...",2020-10-01,monde,L'Express

In [4]:
df_express2 = pd.read_csv('csv/titres_Lexpress2.csv')
df_express2 = df_express2[['titre','jour_publication','categorie']]
df_express2.jour_publication = df_express2.jour_publication.map(lambda x: datetime.datetime.strptime(str(x),'%Y/%m/%d'))
df_express2.categorie = df_express2.categorie.map(lambda x: x.lower())
df_express2['journal']= "L'Express"
df_express2

,titre,jour_publication,categorie,journal
0,Covid-19: Castex justifie les nouvelles restri...,2021-04-01,société,L'Express
1,"Virus : l'Europe tancée par l'OMS, nouvelles r...",2021-04-01,monde,L'Express
2,Manifestation monstre à Hong Kong en 2019: les...,2021-04-01,monde,L'Express
3,La boule à facettes ne brille plus pour Patric...,2021-04-01,société,L'Express
4,Procès Ikea: la défense plaide la relaxe dans ...,2021-04-01,société,L'Express
...,...,...,...,...
1527,"Gülbahar, ""rescapée du goulag chinois"", sidéré...",2021-03-02,monde,L'Express
1528,"Courrier des lecteurs : Eric Zemmour, Covid, A...",2021-03-02,actualité,L'Express
1529,Fiscalité patrimoniale : trois conseils à suiv...,2021-03-02,finances perso,L'Express
1530,Viry-Châtillon: début du procès en appel des a...,2021-03-02,société,L'Express
1531,La Chine réunit sa grand-messe politique annue...,2021-03-02,monde,L'Express

In [7]:
df_express3 = pd.read_csv('csv/titres_Lexpress3.csv')
df_express3bis = pd.read_csv('csv/titres_Lexpress4.csv')
df_express3 =pd.concat([df_express3,df_express3bis])
df_express3 = df_express3[['titre','jour_publication','categorie']]
df_express3.jour_publication = df_express3.jour_publication.map(lambda x: datetime.datetime.strptime(str(x),'%Y/%m/%d'))
df_express3.categorie = df_express3.categorie.map(lambda x: x.lower())
df_express3['journal']= "L'Express"
df_express3

,titre,jour_publication,categorie,journal
0,La Scala retrouve sa splendeur sous les ovatio...,2021-05-10,actualité,L'Express
1,Tapie de retour devant les juges dans l'affair...,2021-05-10,société,L'Express
2,"Covid-19: la France ""en train de sortir"" de la...",2021-05-10,société,L'Express
3,"Afghanistan: après une flambée de violences, l...",2021-05-10,monde,L'Express
4,"Hydratation, le geste forme par excellence",2021-05-10,nutrition,L'Express
...,...,...,...,...
907,Salariés contraints de garder leurs enfants : ...,2020-09-10,société,L'Express
908,"""C'est une sorte de triumvirat qui la prend en...",2020-09-10,droit du travail,L'Express
909,"Covid-19: plus de 900.000 morts, les essais de...",2020-09-10,monde,L'Express
910,Brexit: réunion d'urgence UE-GB pour clarifier...,2020-09-10,monde,L'Express
911,Les deux-tiers de la faune sauvage ont disparu...,2020-09-10,monde,L'Express

In [10]:
df_closer = pd.read_csv('csv/df_closer.csv')
df_closerbis = pd.read_csv('csv/df_closerBis.csv')
df_closer = pd.concat([df_closer,df_closerbis])
df_closer.jour_publication = df_closer.jour_publication.map(lambda x: (datetime.datetime.strptime(x,'%Y/%m/%d') ))
df_closer = df_closer[['titre','jour_publication','categorie']]
df_closer['journal']= "Closer"
df_closer

,titre,jour_publication,categorie,journal
0,Prison ferme pour Nicolas Sarkozy : ces vieux ...,2021-03-02,politique,Closer
1,Brigitte Macron : sa lettre personnelle et tou...,2021-03-02,politique,Closer
2,Gérard Louvin accusé de complicité de viols : ...,2021-03-02,people,Closer
3,Prison ferme pour Nicolas Sarkozy : ces vieux ...,2021-03-01,politique,Closer
4,Brigitte Macron : sa lettre personnelle et tou...,2021-03-01,politique,Closer
...,...,...,...,...
1743,Christina Milian : cet achat complètement impu...,2020-04-01,people,Closer
1744,Matt Pokora confiné : il partage une photo tro...,2020-04-01,people,Closer
1745,"Meghan, Harry et Archie : que font-ils pendant...",2020-04-01,royautes,Closer
1746,Megxit : quels membres de la famille royale su...,2020-04-01,royautes,Closer
1747,"Mort de Pape Diouf : Florian Thauvin, Djibril ...",2020-04-01,people,Closer

In [5]:
df_closer2 = pd.read_csv('csv/df_closer2.csv')
df_closer2 = df_closer2[['titre','jour_publication','categorie']]
df_closer2.jour_publication = df_closer2.jour_publication.map(lambda x: (datetime.datetime.strptime(x,'%Y/%m/%d') ))
df_closer2['journal']= "Closer"
df_closer2

,titre,jour_publication,categorie,journal
0,Jérémy Frérot : l'accouchement de Laure Manaud...,2021-05-10,people,Closer
1,Rachida Dati : qui a volé les clefs de son app...,2021-05-10,politique,Closer
2,Maurane : le touchant hommage de Pascal Obispo...,2021-05-08,people,Closer
3,Gilbert Rozon : l'ex-juré de La France a un in...,2021-05-08,people,Closer
4,Renaud : cet avertissement de Lola Séchan à so...,2021-05-08,people,Closer
...,...,...,...,...
551,Harry et Meghan déchus : quels membres de la f...,2021-03-03,royautes,Closer
552,Nicolas Sarkozy : l'ancien Président explique ...,2021-03-03,politique,Closer
553,Jahmil French : l'acteur de Degrassi : nouvell...,2021-03-03,people,Closer
554,Meghan Markle accusée de harcèlement : les rév...,2021-03-03,royautes,Closer
555,Sylvie Ortega hors de contrôle dans TPMP : la ...,2021-03-03,people,Closer

In [29]:
df = pd.concat([df_lemonde[:8500], df_liberation, df_express,df_closer])
#df.categorie = df.categorie.map(lambda x : x.replace("é","e"))
df

,titre,jour_publication,categorie,journal
0,"Pour les galeries d’art, une situation moins s...",2021-02-01,economie,Le Monde
1,Quand la masturbation provoque une hémorragie ...,2021-02-01,NaN,Le Monde
2,Les pistes de la France pour améliorer les ter...,2021-02-01,economie,Le Monde
3,Facebook et Apple se livrent une guerre ouverte,2021-02-01,economie,Le Monde
4,"Kent Walker : « Google agit selon les lois, et...",2021-02-01,pixels,Le Monde
...,...,...,...,...
1743,Christina Milian : cet achat complètement impu...,2020-04-01,people,Closer
1744,Matt Pokora confiné : il partage une photo tro...,2020-04-01,people,Closer
1745,"Meghan, Harry et Archie : que font-ils pendant...",2020-04-01,royautes,Closer
1746,Megxit : quels membres de la famille royale su...,2020-04-01,royautes,Closer
1747,"Mort de Pape Diouf : Florian Thauvin, Djibril ...",2020-04-01,people,Closer

In [ ]:
df.to_csv('csv/data_cat.csv', index=False)

# dataset 2

In [8]:
df2 = pd.concat([df_lemonde[8500:10500], df_liberation2, df_express2,df_closer2])
df2

,titre,jour_publication,categorie,journal
8500,"« Même si mon conjoint en a fait plus, l’essen...",2020-11-04,emploi,Le Monde
8501,"Pennsylvanie, Michigan, Wisconsin... Le vote o...",2020-11-04,international,Le Monde
8502,Simples spectateurs,2020-11-04,NaN,Le Monde
8503,Ethiopie : le premier ministre annonce une rip...,2020-11-04,afrique,Le Monde
8504,Lagardère : les clans Bolloré et Arnault négoc...,2020-11-04,economie,Le Monde
...,...,...,...,...
551,Harry et Meghan déchus : quels membres de la f...,2021-03-03,royautes,Closer
552,Nicolas Sarkozy : l'ancien Président explique ...,2021-03-03,politique,Closer
553,Jahmil French : l'acteur de Degrassi : nouvell...,2021-03-03,people,Closer
554,Meghan Markle accusée de harcèlement : les rév...,2021-03-03,royautes,Closer
555,Sylvie Ortega hors de contrôle dans TPMP : la ...,2021-03-03,people,Closer

In [9]:
df2.to_csv('csv/data_cat2.csv', index=False)

## Dataset 3

In [9]:
df3 = pd.concat([df_lemonde3,df_lemonde[10500:], df_liberation3, df_express3])
df3

,titre,jour_publication,categorie,journal
0,Castex annonce un durcissement des peines cont...,2021-05-10,societe,Le Monde
1,Nouvel incident dans le détroit d’Ormuz entre ...,2021-05-10,international,Le Monde
2,La France est « en train de sortir durablement...,2021-05-10,planete,Le Monde
3,« Agent orange » : la justice déboute Tran To Nga,2021-05-10,societe,Le Monde
4,Sciences Po tourne la page Olivier Duhamel,2021-05-10,societe,Le Monde
...,...,...,...,...
907,Salariés contraints de garder leurs enfants : ...,2020-09-10,société,L'Express
908,"""C'est une sorte de triumvirat qui la prend en...",2020-09-10,droit du travail,L'Express
909,"Covid-19: plus de 900.000 morts, les essais de...",2020-09-10,monde,L'Express
910,Brexit: réunion d'urgence UE-GB pour clarifier...,2020-09-10,monde,L'Express
911,Les deux-tiers de la faune sauvage ont disparu...,2020-09-10,monde,L'Express

In [10]:
df3.to_csv('csv/data_cat3.csv', index=False)

In [4]:
df_liberation4.to_csv('csv/data_cat4.csv', index=False)