In [6]:
import sklearn
import numpy as np

import pandas as pd
import datetime
import time
import pickle
import mlflow
import mlflow.sklearn

In [7]:
df = pd.read_csv('data.csv')
df

,titre,jour_publication,auteur,journal
0,"Pour les galeries d’art, une situation moins s...",01-02-2021,['Roxana Azimi'],Le Monde
1,Quand la masturbation provoque une hémorragie ...,01-02-2021,['Marc Gozlan'],Le Monde
2,Les pistes de la France pour améliorer les ter...,01-02-2021,['Julien Bouissou'],Le Monde
3,Facebook et Apple se livrent une guerre ouverte,01-02-2021,['Alexandre Piquard'],Le Monde
4,"Kent Walker : « Google agit selon les lois, et...",01-02-2021,['Kent Walker'],Le Monde
...,...,...,...,...
46931,Christina Milian : cet achat complètement impu...,2020/04/01,NaN,Closer
46932,Matt Pokora confiné : il partage une photo tro...,2020/04/01,NaN,Closer
46933,"Meghan, Harry et Archie : que font-ils pendant...",2020/04/01,NaN,Closer
46934,Megxit : quels membres de la famille royale su...,2020/04/01,NaN,Closer
46935,"Mort de Pape Diouf : Florian Thauvin, Djibril ...",2020/04/01,NaN,Closer

In [10]:
with mlflow.start_run():
    long = len(df)
    mlflow.log_metric('observation',long)